apiVersion: batch/v1
kind: Job
metadata:
  name: kgbk271-trident-gigapath
  namespace: ibd-plexus-research
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: default-editor
      restartPolicy: Never
      tolerations:
        - effect: NoSchedule
          key: GPU_workload
          operator: Equal
          value: "true"
      volumes:
        - name: kgbk271-ibd-volume
          persistentVolumeClaim:
            claimName: kgbk271-ibd-volume
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
        - name: kgbk271-ibd-workspace
          persistentVolumeClaim:
            claimName: kgbk271-ibd-workspace
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      containers:
        - name: trident-gigapath
          image: harbor.csis.astrazeneca.net/azimuth-demo/cpu-codeserver:latest
          command:
            - /bin/bash
            - -c
            - |
              /home/jovyan/kgbk271-ibd-volume/envs/trident/bin/python \
                /home/jovyan/shared-data/users/kexin/models/trident/run_batch_of_slides.py \
                --task all \
                --wsi_dir /home/jovyan/kgbk271-ibd-volume/data/raw/tiff_mpp_corrected \
                --job_dir /home/jovyan/kgbk271-ibd-volume/data/processed/trident_processed \
                --slide_encoder gigapath \
                --patch_encoder gigapath \
                --patch_size 256 \
                --mag 20 \
                --batch_size 256 \
                --gpus 0 \
                --skip_errors \
                --clear_dead_locks
          resources:
            requests:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "16"
              memory: 64Gi
              nvidia.com/gpu: "1"
          env:
            - name: http_proxy
              value: "http://azpse.astrazeneca.net:9480"
            - name: https_proxy
              value: "http://azpse.astrazeneca.net:9480"
            - name: no_proxy
              value: "localhost,127.0.0.1,.svc.cluster.local,kubernetes.default.svc,astrazeneca.net,::1,10.0.0.0/8,172.30.0.0/8,172.29.0.0/8"
            - name: HF_HOME
              value: "/home/jovyan/kgbk271-ibd-volume/hf_cache"
            - name: HF_HUB_CACHE
              value: "/home/jovyan/kgbk271-ibd-volume/hf_cache"
            - name: TRANSFORMERS_CACHE
              value: "/home/jovyan/kgbk271-ibd-volume/hf_cache"
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: TRANSFORMERS_OFFLINE
              value: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: kgbk271-ibd-volume
              mountPath: /home/jovyan/kgbk271-ibd-volume
            - name: shared-data
              mountPath: /home/jovyan/shared-data
            - name: kgbk271-ibd-workspace
              mountPath: /home/jovyan
