apiVersion: batch/v1
kind: Job
metadata:
  name: kgbk271-umap-rna
  namespace: ibd-plexus-research
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default-editor
      restartPolicy: Never
      volumes:
        - name: kgbk271-ibd-volume
          persistentVolumeClaim:
            claimName: kgbk271-ibd-volume
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
        - name: kgbk271-ibd-workspace
          persistentVolumeClaim:
            claimName: kgbk271-ibd-workspace
      containers:
        - name: umap-rna
          image: harbor.csis.astrazeneca.net/azimuth-demo/cpu-codeserver:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              pip install numpy pandas matplotlib scikit-learn umap-learn plotly \
                --quiet --no-cache-dir
              python /home/jovyan/ibdplexus/code/training/cd_vs_uc/umap_rna.py
          resources:
            requests:
              cpu: "1"
              memory: 10Gi
            limits:
              cpu: "2"
              memory: 10Gi
          env:
            - name: http_proxy
              value: "http://azpse.astrazeneca.net:9480"
            - name: https_proxy
              value: "http://azpse.astrazeneca.net:9480"
            - name: no_proxy
              value: "localhost,127.0.0.1,.svc.cluster.local,kubernetes.default.svc,astrazeneca.net,::1,10.0.0.0/8,172.30.0.0/8,172.29.0.0/8"
          volumeMounts:
            - name: kgbk271-ibd-volume
              mountPath: /home/jovyan/kgbk271-ibd-volume
            - name: shared-data
              mountPath: /home/jovyan/shared-data
            - name: kgbk271-ibd-workspace
              mountPath: /home/jovyan
